# deepspeed --master_port=29498 main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/clinc150/full/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 5e-5 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6
# deepspeed --master_port=29498 main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/clinc150/full/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 2e-4 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6

# deepspeed --master_port=29498 main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/clinc150/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 1e-4 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
deepspeed --master_port=29498 main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/clinc150/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 5e-5 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
deepspeed --master_port=29498 main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/clinc150/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 2e-4 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
# deepspeed --master_port=29498 main_ood.py --task_name banking77 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/banking77/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 5e-5 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
# deepspeed --master_port=29498 main_ood.py --task_name banking77 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/banking77/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 1e-4 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
deepspeed --master_port=29498 main_ood.py --task_name banking77 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --output_dir outputs/banking77/0.25/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir model_data_gpt_neo_2.7B --lr 2e-4 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --split --split_ratio 0.25
# deepspeed --master_port=29498 --include="localhost:1" main_ood.py --task_name clinc150 --overwrite_output_dir --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero3_config.json --output_dir outputs/clinc150/full/gpt-neo-2.7B/adapter --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.00016 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400 --apply_adapter --adapter_size 6 --gradient_accumulation_steps 2

# deepspeed main_ood_param_check.py --split --task_name banking77 --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero3_config.json --output_dir outputs/banking77/0.5/gpt-neo-2.7B --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.00016 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400
# deepspeed main_ood_param_check.py --split --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero3_config.json --output_dir outputs/clinc150/0.5/gpt-neo-2.7B --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.00016 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400
# deepspeed main_ood_param_check.py --split --task_name snips --model_name_or_path EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero3_config.json --output_dir outputs/snips/0.5/gpt-neo-2.7B --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.00016 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 400