deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.001 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.001 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.001 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.001 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 40
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 40
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 40
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 40
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 5e-05 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 81
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 5e-05 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 81
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 5e-05 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 81
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 5e-05 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 81
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 8
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 82
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 82
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 82
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path EleutherAI/gpt-neo-2.7B --output_dir outputs_best/clinc150/full/EleutherAI/gpt-neo-2.7B --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.0005 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 82
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 3
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 17
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 31
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 31
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 31
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 31
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 64
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 64
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 64
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2 --output_dir outputs_best/clinc150/full/gpt2 --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 64
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 21
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 42
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 7
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 7
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 7
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 7
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 41
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 83
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 83
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 83
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-large --output_dir outputs_best/clinc150/full/gpt2-large --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 83
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 4
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 18
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 36
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 6
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 6
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 6
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 6
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 34
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 70
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 70
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 70
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-medium --output_dir outputs_best/clinc150/full/gpt2-medium --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 70
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_adapter --adapter_size 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_adapter --adapter_size 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_adapter --adapter_size 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_adapter --adapter_size 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 5
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 25
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_lora --lora_r 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_lora --lora_r 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_lora --lora_r 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_lora --lora_r 51
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 9
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 9
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 9
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 9
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 50
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 50
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 50
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 50
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1 --apply_prefix --num_prefix 10 --mid_dim 100
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 7 --apply_prefix --num_prefix 10 --mid_dim 100
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 123 --apply_prefix --num_prefix 10 --mid_dim 100
deepspeed --include localhost:1,2 --master_port 24998 main_ood.py --overwrite_output_dir --task_name clinc150 --model_name_or_path gpt2-xl --output_dir outputs_best/clinc150/full/gpt2-xl --ds_config ds_configs_samples/zero2_config.json --num_train_epochs 40 --cache_dir ~/data/model_data --lr 0.002 --weight_decay 0.1 --lr_scheduler_type cosine --num_warmup_steps 200 --seed 1234 --apply_prefix --num_prefix 10 --mid_dim 100
